#ifndef TEST_H_GENERATED_
#define TEST_H_GENERATED_
/* Automically generated by wasm2c */
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#include "wasm-rt.h"

#ifndef WASM_RT_MODULE_PREFIX
#define WASM_RT_MODULE_PREFIX
#endif

#define WASM_RT_PASTE_(x, y) x ## y
#define WASM_RT_PASTE(x, y) WASM_RT_PASTE_(x, y)
#define WASM_RT_ADD_PREFIX(x) WASM_RT_PASTE(WASM_RT_MODULE_PREFIX, x)

/* TODO(binji): only use stdint.h types in header */
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;

extern void WASM_RT_ADD_PREFIX(init)(void);

/* import: 'arduino' 'numPixels' */
extern u32 (*Z_arduinoZ_numPixelsZ_iv)(void);
/* import: 'arduino' 'setPixelColor32' */
extern void (*Z_arduinoZ_setPixelColor32Z_vii)(u32, u32);
/* import: 'arduino' 'show' */
extern void (*Z_arduinoZ_showZ_vv)(void);
/* import: 'arduino' 'delay' */
extern void (*Z_arduinoZ_delayZ_vi)(u32);
/* import: 'arduino' 'Wheel' */
extern u32 (*Z_arduinoZ_WheelZ_ii)(u32);
/* import: 'arduino' 'print' */
extern void (*Z_arduinoZ_printZ_vii)(u32, u32);
/* import: 'arduino' 'Color' */
extern u32 (*Z_arduinoZ_ColorZ_iiii)(u32, u32, u32);

/* export: 'memory' */
extern wasm_rt_memory_t (*WASM_RT_ADD_PREFIX(Z_memory));
/* export: '_start' */
extern void (*WASM_RT_ADD_PREFIX(Z__startZ_vv))(void);
/* export: 'setup' */
extern void (*WASM_RT_ADD_PREFIX(Z_setupZ_vv))(void);
/* export: 'loop' */
extern void (*WASM_RT_ADD_PREFIX(Z_loopZ_vv))(void);
#ifdef __cplusplus
}
#endif

#endif  /* TEST_H_GENERATED_ */
