/* Automically generated by wasm2c */
#include <math.h>
#include <string.h>

#include "test.h"
#define UNLIKELY(x) __builtin_expect(!!(x), 0)
#define LIKELY(x) __builtin_expect(!!(x), 1)

#define TRAP(x) (wasm_rt_trap(WASM_RT_TRAP_##x), 0)

#define FUNC_PROLOGUE                                            \
  if (++wasm_rt_call_stack_depth > WASM_RT_MAX_CALL_STACK_DEPTH) \
    TRAP(EXHAUSTION)

#define FUNC_EPILOGUE --wasm_rt_call_stack_depth

#define UNREACHABLE TRAP(UNREACHABLE)

#define CALL_INDIRECT(table, t, ft, x, ...)          \
  (LIKELY((x) < table.size && table.data[x].func &&  \
          table.data[x].func_type == func_types[ft]) \
       ? ((t)table.data[x].func)(__VA_ARGS__)        \
       : TRAP(CALL_INDIRECT))

#if WASM_RT_MEMCHECK_SIGNAL_HANDLER
#define MEMCHECK(mem, a, t)
#else
#define MEMCHECK(mem, a, t)  \
  if (UNLIKELY((a) + sizeof(t) > mem->size)) TRAP(OOB)
#endif

#if WABT_BIG_ENDIAN
static inline void load_data(void *dest, const void *src, size_t n) {
  size_t i = 0;
  u8 *dest_chars = dest;
  memcpy(dest, src, n);
  for (i = 0; i < (n>>1); i++) {
    u8 cursor = dest_chars[i];
    dest_chars[i] = dest_chars[n - i - 1];
    dest_chars[n - i - 1] = cursor;
  }
}
#define LOAD_DATA(m, o, i, s) load_data(&(m.data[m.size - o - s]), i, s)
#define DEFINE_LOAD(name, t1, t2, t3)                                                 \
  static inline t3 name(wasm_rt_memory_t* mem, u64 addr) {                            \
    MEMCHECK(mem, addr, t1);                                                          \
    t1 result;                                                                        \
    __builtin_memcpy(&result, &mem->data[mem->size - addr - sizeof(t1)], sizeof(t1)); \
    return (t3)(t2)result;                                                            \
  }

#define DEFINE_STORE(name, t1, t2)                                                     \
  static inline void name(wasm_rt_memory_t* mem, u64 addr, t2 value) {                 \
    MEMCHECK(mem, addr, t1);                                                           \
    t1 wrapped = (t1)value;                                                            \
    __builtin_memcpy(&mem->data[mem->size - addr - sizeof(t1)], &wrapped, sizeof(t1)); \
  }
#else
static inline void load_data(void *dest, const void *src, size_t n) {
  memcpy(dest, src, n);
}
#define LOAD_DATA(m, o, i, s) load_data(&(m.data[o]), i, s)
#define DEFINE_LOAD(name, t1, t2, t3)                        \
  static inline t3 name(wasm_rt_memory_t* mem, u64 addr) {   \
    MEMCHECK(mem, addr, t1);                                 \
    t1 result;                                               \
    __builtin_memcpy(&result, &mem->data[addr], sizeof(t1)); \
    return (t3)(t2)result;                                   \
  }

#define DEFINE_STORE(name, t1, t2)                                     \
  static inline void name(wasm_rt_memory_t* mem, u64 addr, t2 value) { \
    MEMCHECK(mem, addr, t1);                                           \
    t1 wrapped = (t1)value;                                            \
    __builtin_memcpy(&mem->data[addr], &wrapped, sizeof(t1));          \
  }
#endif

DEFINE_LOAD(i32_load, u32, u32, u32);
DEFINE_LOAD(i64_load, u64, u64, u64);
DEFINE_LOAD(f32_load, f32, f32, f32);
DEFINE_LOAD(f64_load, f64, f64, f64);
DEFINE_LOAD(i32_load8_s, s8, s32, u32);
DEFINE_LOAD(i64_load8_s, s8, s64, u64);
DEFINE_LOAD(i32_load8_u, u8, u32, u32);
DEFINE_LOAD(i64_load8_u, u8, u64, u64);
DEFINE_LOAD(i32_load16_s, s16, s32, u32);
DEFINE_LOAD(i64_load16_s, s16, s64, u64);
DEFINE_LOAD(i32_load16_u, u16, u32, u32);
DEFINE_LOAD(i64_load16_u, u16, u64, u64);
DEFINE_LOAD(i64_load32_s, s32, s64, u64);
DEFINE_LOAD(i64_load32_u, u32, u64, u64);
DEFINE_STORE(i32_store, u32, u32);
DEFINE_STORE(i64_store, u64, u64);
DEFINE_STORE(f32_store, f32, f32);
DEFINE_STORE(f64_store, f64, f64);
DEFINE_STORE(i32_store8, u8, u32);
DEFINE_STORE(i32_store16, u16, u32);
DEFINE_STORE(i64_store8, u8, u64);
DEFINE_STORE(i64_store16, u16, u64);
DEFINE_STORE(i64_store32, u32, u64);

#define I32_CLZ(x) ((x) ? __builtin_clz(x) : 32)
#define I64_CLZ(x) ((x) ? __builtin_clzll(x) : 64)
#define I32_CTZ(x) ((x) ? __builtin_ctz(x) : 32)
#define I64_CTZ(x) ((x) ? __builtin_ctzll(x) : 64)
#define I32_POPCNT(x) (__builtin_popcount(x))
#define I64_POPCNT(x) (__builtin_popcountll(x))

#define DIV_S(ut, min, x, y)                                 \
   ((UNLIKELY((y) == 0)) ?                TRAP(DIV_BY_ZERO)  \
  : (UNLIKELY((x) == min && (y) == -1)) ? TRAP(INT_OVERFLOW) \
  : (ut)((x) / (y)))

#define REM_S(ut, min, x, y)                                \
   ((UNLIKELY((y) == 0)) ?                TRAP(DIV_BY_ZERO) \
  : (UNLIKELY((x) == min && (y) == -1)) ? 0                 \
  : (ut)((x) % (y)))

#define I32_DIV_S(x, y) DIV_S(u32, INT32_MIN, (s32)x, (s32)y)
#define I64_DIV_S(x, y) DIV_S(u64, INT64_MIN, (s64)x, (s64)y)
#define I32_REM_S(x, y) REM_S(u32, INT32_MIN, (s32)x, (s32)y)
#define I64_REM_S(x, y) REM_S(u64, INT64_MIN, (s64)x, (s64)y)

#define DIVREM_U(op, x, y) \
  ((UNLIKELY((y) == 0)) ? TRAP(DIV_BY_ZERO) : ((x) op (y)))

#define DIV_U(x, y) DIVREM_U(/, x, y)
#define REM_U(x, y) DIVREM_U(%, x, y)

#define ROTL(x, y, mask) \
  (((x) << ((y) & (mask))) | ((x) >> (((mask) - (y) + 1) & (mask))))
#define ROTR(x, y, mask) \
  (((x) >> ((y) & (mask))) | ((x) << (((mask) - (y) + 1) & (mask))))

#define I32_ROTL(x, y) ROTL(x, y, 31)
#define I64_ROTL(x, y) ROTL(x, y, 63)
#define I32_ROTR(x, y) ROTR(x, y, 31)
#define I64_ROTR(x, y) ROTR(x, y, 63)

#define FMIN(x, y)                                          \
   ((UNLIKELY((x) != (x))) ? NAN                            \
  : (UNLIKELY((y) != (y))) ? NAN                            \
  : (UNLIKELY((x) == 0 && (y) == 0)) ? (signbit(x) ? x : y) \
  : (x < y) ? x : y)

#define FMAX(x, y)                                          \
   ((UNLIKELY((x) != (x))) ? NAN                            \
  : (UNLIKELY((y) != (y))) ? NAN                            \
  : (UNLIKELY((x) == 0 && (y) == 0)) ? (signbit(x) ? y : x) \
  : (x > y) ? x : y)

#define TRUNC_S(ut, st, ft, min, minop, max, x)                             \
  ((UNLIKELY((x) != (x)))                        ? TRAP(INVALID_CONVERSION) \
   : (UNLIKELY(!((x)minop(min) && (x) < (max)))) ? TRAP(INT_OVERFLOW)       \
                                                 : (ut)(st)(x))

#define I32_TRUNC_S_F32(x) TRUNC_S(u32, s32, f32, (f32)INT32_MIN, >=, 2147483648.f, x)
#define I64_TRUNC_S_F32(x) TRUNC_S(u64, s64, f32, (f32)INT64_MIN, >=, (f32)INT64_MAX, x)
#define I32_TRUNC_S_F64(x) TRUNC_S(u32, s32, f64, -2147483649., >, 2147483648., x)
#define I64_TRUNC_S_F64(x) TRUNC_S(u64, s64, f64, (f64)INT64_MIN, >=, (f64)INT64_MAX, x)

#define TRUNC_U(ut, ft, max, x)                                            \
  ((UNLIKELY((x) != (x)))                       ? TRAP(INVALID_CONVERSION) \
   : (UNLIKELY(!((x) > (ft)-1 && (x) < (max)))) ? TRAP(INT_OVERFLOW)       \
                                                : (ut)(x))

#define I32_TRUNC_U_F32(x) TRUNC_U(u32, f32, 4294967296.f, x)
#define I64_TRUNC_U_F32(x) TRUNC_U(u64, f32, (f32)UINT64_MAX, x)
#define I32_TRUNC_U_F64(x) TRUNC_U(u32, f64, 4294967296.,  x)
#define I64_TRUNC_U_F64(x) TRUNC_U(u64, f64, (f64)UINT64_MAX, x)

#define DEFINE_REINTERPRET(name, t1, t2)  \
  static inline t2 name(t1 x) {           \
    t2 result;                            \
    memcpy(&result, &x, sizeof(result));  \
    return result;                        \
  }

DEFINE_REINTERPRET(f32_reinterpret_i32, u32, f32)
DEFINE_REINTERPRET(i32_reinterpret_f32, f32, u32)
DEFINE_REINTERPRET(f64_reinterpret_i64, u64, f64)
DEFINE_REINTERPRET(i64_reinterpret_f64, f64, u64)


static u32 func_types[6];

static void init_func_types(void) {
  func_types[0] = wasm_rt_register_func_type(0, 0);
  func_types[1] = wasm_rt_register_func_type(2, 0, WASM_RT_I32, WASM_RT_I32);
  func_types[2] = wasm_rt_register_func_type(1, 0, WASM_RT_I32);
  func_types[3] = wasm_rt_register_func_type(0, 1, WASM_RT_I32);
  func_types[4] = wasm_rt_register_func_type(1, 1, WASM_RT_I32, WASM_RT_I32);
  func_types[5] = wasm_rt_register_func_type(3, 1, WASM_RT_I32, WASM_RT_I32, WASM_RT_I32, WASM_RT_I32);
}

static void w2c__start(void);
static void w2c_f8(u32);
static void w2c_setup(void);
static void w2c_loop(void);

static void init_globals(void) {
}

static wasm_rt_memory_t w2c_memory;

static void w2c__start(void) {
  FUNC_PROLOGUE;
  FUNC_EPILOGUE;
}

static void w2c_f8(u32 w2c_p0) {
  u32 w2c_l1 = 0;
  FUNC_PROLOGUE;
  u32 w2c_i0, w2c_i1, w2c_i2;
  w2c_i0 = (*Z_arduinoZ_numPixelsZ_iv)();
  if (w2c_i0) {
    w2c_L1: 
      w2c_i0 = w2c_l1;
      w2c_i1 = 65535u;
      w2c_i0 &= w2c_i1;
      w2c_i1 = w2c_p0;
      (*Z_arduinoZ_setPixelColor32Z_vii)(w2c_i0, w2c_i1);
      (*Z_arduinoZ_showZ_vv)();
      w2c_i0 = 50u;
      (*Z_arduinoZ_delayZ_vi)(w2c_i0);
      w2c_i0 = (*Z_arduinoZ_numPixelsZ_iv)();
      w2c_i1 = w2c_l1;
      w2c_i2 = 1u;
      w2c_i1 += w2c_i2;
      w2c_l1 = w2c_i1;
      w2c_i2 = 65535u;
      w2c_i1 &= w2c_i2;
      w2c_i0 = w2c_i0 > w2c_i1;
      if (w2c_i0) {goto w2c_L1;}
  }
  FUNC_EPILOGUE;
}

static void w2c_setup(void) {
  FUNC_PROLOGUE;
  u32 w2c_i0, w2c_i1;
  w2c_i0 = 1024u;
  w2c_i1 = 21u;
  (*Z_arduinoZ_printZ_vii)(w2c_i0, w2c_i1);
  w2c_i0 = 1119u;
  w2c_i1 = 1u;
  (*Z_arduinoZ_printZ_vii)(w2c_i0, w2c_i1);
  FUNC_EPILOGUE;
}

static void w2c_loop(void) {
  u32 w2c_l0 = 0, w2c_l1 = 0, w2c_l2 = 0, w2c_l3 = 0;
  FUNC_PROLOGUE;
  u32 w2c_i0, w2c_i1, w2c_i2;
  w2c_i0 = 1046u;
  w2c_i1 = 14u;
  (*Z_arduinoZ_printZ_vii)(w2c_i0, w2c_i1);
  w2c_i0 = 1119u;
  w2c_i1 = 1u;
  (*Z_arduinoZ_printZ_vii)(w2c_i0, w2c_i1);
  w2c_i0 = 255u;
  w2c_i1 = 0u;
  w2c_i2 = 0u;
  w2c_i0 = (*Z_arduinoZ_ColorZ_iiii)(w2c_i0, w2c_i1, w2c_i2);
  w2c_f8(w2c_i0);
  w2c_i0 = 0u;
  w2c_i1 = 255u;
  w2c_i2 = 0u;
  w2c_i0 = (*Z_arduinoZ_ColorZ_iiii)(w2c_i0, w2c_i1, w2c_i2);
  w2c_f8(w2c_i0);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i2 = 255u;
  w2c_i0 = (*Z_arduinoZ_ColorZ_iiii)(w2c_i0, w2c_i1, w2c_i2);
  w2c_f8(w2c_i0);
  w2c_i0 = 1061u;
  w2c_i1 = 12u;
  (*Z_arduinoZ_printZ_vii)(w2c_i0, w2c_i1);
  w2c_i0 = 1119u;
  w2c_i1 = 1u;
  (*Z_arduinoZ_printZ_vii)(w2c_i0, w2c_i1);
  w2c_L0: 
    w2c_i0 = (*Z_arduinoZ_numPixelsZ_iv)();
    if (w2c_i0) {
      w2c_i0 = 0u;
      w2c_l0 = w2c_i0;
      w2c_L2: 
        w2c_i0 = w2c_l0;
        w2c_i1 = 65535u;
        w2c_i0 &= w2c_i1;
        w2c_i1 = w2c_l0;
        w2c_i2 = w2c_l1;
        w2c_i1 += w2c_i2;
        w2c_i2 = 255u;
        w2c_i1 &= w2c_i2;
        w2c_i1 = (*Z_arduinoZ_WheelZ_ii)(w2c_i1);
        (*Z_arduinoZ_setPixelColor32Z_vii)(w2c_i0, w2c_i1);
        w2c_i0 = (*Z_arduinoZ_numPixelsZ_iv)();
        w2c_i1 = w2c_l0;
        w2c_i2 = 1u;
        w2c_i1 += w2c_i2;
        w2c_l0 = w2c_i1;
        w2c_i2 = 65535u;
        w2c_i1 &= w2c_i2;
        w2c_i0 = w2c_i0 > w2c_i1;
        if (w2c_i0) {goto w2c_L2;}
    }
    (*Z_arduinoZ_showZ_vv)();
    w2c_i0 = 20u;
    (*Z_arduinoZ_delayZ_vi)(w2c_i0);
    w2c_i0 = w2c_l1;
    w2c_i1 = 1u;
    w2c_i0 += w2c_i1;
    w2c_l1 = w2c_i0;
    w2c_i1 = 65535u;
    w2c_i0 &= w2c_i1;
    w2c_i1 = 256u;
    w2c_i0 = w2c_i0 < w2c_i1;
    if (w2c_i0) {goto w2c_L0;}
  w2c_i0 = 1074u;
  w2c_i1 = 24u;
  (*Z_arduinoZ_printZ_vii)(w2c_i0, w2c_i1);
  w2c_i0 = 1119u;
  w2c_i1 = 1u;
  (*Z_arduinoZ_printZ_vii)(w2c_i0, w2c_i1);
  w2c_L3: 
    w2c_i0 = 0u;
    w2c_l2 = w2c_i0;
    w2c_L4: 
      w2c_i0 = (*Z_arduinoZ_numPixelsZ_iv)();
      if (w2c_i0) {
        w2c_i0 = 0u;
        w2c_l0 = w2c_i0;
        w2c_i0 = 0u;
        w2c_l1 = w2c_i0;
        w2c_L6: 
          w2c_i0 = w2c_l1;
          w2c_i1 = w2c_l2;
          w2c_i0 += w2c_i1;
          w2c_i1 = 65535u;
          w2c_i0 &= w2c_i1;
          w2c_i1 = w2c_l0;
          w2c_i2 = w2c_l3;
          w2c_i1 += w2c_i2;
          w2c_i2 = 255u;
          w2c_i1 = REM_U(w2c_i1, w2c_i2);
          w2c_i1 = (*Z_arduinoZ_WheelZ_ii)(w2c_i1);
          (*Z_arduinoZ_setPixelColor32Z_vii)(w2c_i0, w2c_i1);
          w2c_i0 = (*Z_arduinoZ_numPixelsZ_iv)();
          w2c_i1 = w2c_l0;
          w2c_i2 = 3u;
          w2c_i1 += w2c_i2;
          w2c_l1 = w2c_i1;
          w2c_i2 = 65535u;
          w2c_i1 &= w2c_i2;
          w2c_l0 = w2c_i1;
          w2c_i0 = w2c_i0 > w2c_i1;
          if (w2c_i0) {goto w2c_L6;}
      }
      (*Z_arduinoZ_showZ_vv)();
      w2c_i0 = 20u;
      (*Z_arduinoZ_delayZ_vi)(w2c_i0);
      w2c_i0 = (*Z_arduinoZ_numPixelsZ_iv)();
      if (w2c_i0) {
        w2c_i0 = 0u;
        w2c_l0 = w2c_i0;
        w2c_i0 = 0u;
        w2c_l1 = w2c_i0;
        w2c_L8: 
          w2c_i0 = w2c_l1;
          w2c_i1 = w2c_l2;
          w2c_i0 += w2c_i1;
          w2c_i1 = 65535u;
          w2c_i0 &= w2c_i1;
          w2c_i1 = 0u;
          (*Z_arduinoZ_setPixelColor32Z_vii)(w2c_i0, w2c_i1);
          w2c_i0 = (*Z_arduinoZ_numPixelsZ_iv)();
          w2c_i1 = w2c_l0;
          w2c_i2 = 3u;
          w2c_i1 += w2c_i2;
          w2c_l1 = w2c_i1;
          w2c_i2 = 65535u;
          w2c_i1 &= w2c_i2;
          w2c_l0 = w2c_i1;
          w2c_i0 = w2c_i0 > w2c_i1;
          if (w2c_i0) {goto w2c_L8;}
      }
      w2c_i0 = w2c_l2;
      w2c_i1 = 1u;
      w2c_i0 += w2c_i1;
      w2c_l2 = w2c_i0;
      w2c_i1 = 3u;
      w2c_i0 = w2c_i0 != w2c_i1;
      if (w2c_i0) {goto w2c_L4;}
    w2c_i0 = w2c_l3;
    w2c_i1 = 1u;
    w2c_i0 += w2c_i1;
    w2c_l3 = w2c_i0;
    w2c_i1 = 256u;
    w2c_i0 = w2c_i0 != w2c_i1;
    if (w2c_i0) {goto w2c_L3;}
  w2c_i0 = 1099u;
  w2c_i1 = 19u;
  (*Z_arduinoZ_printZ_vii)(w2c_i0, w2c_i1);
  w2c_i0 = 1119u;
  w2c_i1 = 1u;
  (*Z_arduinoZ_printZ_vii)(w2c_i0, w2c_i1);
  FUNC_EPILOGUE;
}

static const u8 data_segment_data_0[] = {
  0x0a, 0x73, 0x74, 0x72, 0x61, 0x6e, 0x64, 0x74, 0x65, 0x73, 0x74, 0x20, 
  0x2e, 0x2e, 0x2e, 0x20, 0x73, 0x74, 0x61, 0x72, 0x74, 0x00, 0x63, 0x6f, 
  0x6c, 0x6f, 0x72, 0x57, 0x69, 0x70, 0x65, 0x20, 0x2e, 0x2e, 0x2e, 0x20, 
  0x00, 0x72, 0x61, 0x69, 0x6e, 0x62, 0x6f, 0x77, 0x20, 0x2e, 0x2e, 0x2e, 
  0x20, 0x00, 0x74, 0x68, 0x65, 0x61, 0x74, 0x65, 0x72, 0x43, 0x68, 0x61, 
  0x73, 0x65, 0x52, 0x61, 0x69, 0x6e, 0x62, 0x6f, 0x77, 0x20, 0x2e, 0x2e, 
  0x2e, 0x20, 0x00, 0x73, 0x74, 0x72, 0x61, 0x6e, 0x64, 0x74, 0x65, 0x73, 
  0x74, 0x20, 0x2e, 0x2e, 0x2e, 0x20, 0x6c, 0x6f, 0x6f, 0x70, 0x00, 0x0a, 
  
};

static void init_memory(void) {
  wasm_rt_allocate_memory((&w2c_memory), 1, 65536);
  LOAD_DATA(w2c_memory, 1024u, data_segment_data_0, 96);
}

static void init_table(void) {
  uint32_t offset;
}

/* export: 'memory' */
wasm_rt_memory_t (*WASM_RT_ADD_PREFIX(Z_memory));
/* export: '_start' */
void (*WASM_RT_ADD_PREFIX(Z__startZ_vv))(void);
/* export: 'setup' */
void (*WASM_RT_ADD_PREFIX(Z_setupZ_vv))(void);
/* export: 'loop' */
void (*WASM_RT_ADD_PREFIX(Z_loopZ_vv))(void);

static void init_exports(void) {
  /* export: 'memory' */
  WASM_RT_ADD_PREFIX(Z_memory) = (&w2c_memory);
  /* export: '_start' */
  WASM_RT_ADD_PREFIX(Z__startZ_vv) = (&w2c__start);
  /* export: 'setup' */
  WASM_RT_ADD_PREFIX(Z_setupZ_vv) = (&w2c_setup);
  /* export: 'loop' */
  WASM_RT_ADD_PREFIX(Z_loopZ_vv) = (&w2c_loop);
}

void WASM_RT_ADD_PREFIX(init)(void) {
  init_func_types();
  init_globals();
  init_memory();
  init_table();
  init_exports();
}
